name: Palindrome CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: Test_first_function
      run: ./palindrome f 1
    - name: Test_first_function_2
      run: ./palindrome f 5
    - name: Test_first_function_3
      run: ./palindrome f
    - name: Test_first_function_4
      run: ./palindrome f 13
    - name: Test_second_function
      run: ./palindrome s 1
    - name: Test_second_function_2
      run: ./palindrome s 5
    - name: Test_second_function_3
      run: ./palindrome s
    - name: Test_second_function_4
      run: ./palindrome s 14
