name: Palindrome CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: Test Palindrome with a base of 10
      run: ./palindrome -n 4782 -b 10
    - name: Test Palindrome with a base of 2
      run: ./palindrome -n 64 -b 2
    - name: Test palindrome with -p option
      run: ./palindrome -p 363 -b 10
    - name: Test Palindrome with -imax option
      run: ./palindrome -p 363 -b 10 -imax 2
    - name: Test Palindrome with -imin option
      run: ./palindrome -p 363 -b 10 -imin 6
    - name: Test Palindrome with bad arguments
      run: ./palindrome -n 4782 toto
      continue-on-error: true
    - name: Test Palindrome but with a result of "no solution"
      run: ./palindrome -p 363 -b 10 -imin 7
